name: Release
on:
  push:
    branches:
      - master
      - next
      - main
jobs:
  release:
    runs-on: ubuntu-latest
    permissions: write-all
    if: github.repository == 'boyney123/cloudcatalog'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          version: 18.x

      - name: Install deps
        run: npm install

      - name: Create Release Pull Request or Publish to npm
        uses: changesets/action@v1
        with:
          publish: npm run publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
